#!/bin/bash
# setup-pre-commit.sh — 安裝 pre-commit hook 自動跑 link check
#
# 用法：./scripts/setup-pre-commit.sh

set -euo pipefail

cd "$(dirname "$0")/.."

HOOK_FILE=".git/hooks/pre-commit"

if [ ! -d ".git" ]; then
    echo "❌ 不在 git repo 內、先跑 git init"
    exit 1
fi

if [ -f "$HOOK_FILE" ]; then
    echo "⚠️  pre-commit hook 已存在：$HOOK_FILE"
    read -p "覆蓋？[y/N] " -r
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

cat > "$HOOK_FILE" <<'HOOK_EOF'
#!/bin/bash
# Auto-generated by ProposalOS setup-pre-commit.sh

set -e

# 跑 link check
echo "🔗 Pre-commit: checking markdown internal links..."
./scripts/check-links.sh || {
    echo ""
    echo "❌ Pre-commit failed: 有 broken internal links"
    echo "   修完 link 再 commit、或用 git commit --no-verify 跳過（不建議）"
    exit 1
}

echo "✅ Pre-commit checks passed"
HOOK_EOF

chmod +x "$HOOK_FILE"

echo "✅ pre-commit hook 已安裝：$HOOK_FILE"
echo ""
echo "下次 git commit 會自動跑 scripts/check-links.sh"
echo "失敗時、修完 link 再 commit"
echo ""
echo "緊急跳過：git commit --no-verify（不建議）"
